# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-lambda-chaining
# app and org for use with dashboard.serverless.com
app: serverless-lambda-chaining
org: yukliadev

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage,'dev'}
  # ! You can publish messages only to topics and endpoints in the same AWS Region.
  region: ${opt:region, 'eu-west-3'}  
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

custom:
  snsTopicForConsumer1: "${self:service}-${self:provider.stage}-sns-consumer1"
  snsTopicForConsumer1Arn:
    dev:
      { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.snsTopicForConsumer1}" ] ]  }
  snsTopicForConsumer2: "${self:service}-${self:provider.stage}-sns-consumer2"
  snsTopicForConsumer2Arn:
    dev:
      { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.snsTopicForConsumer2}" ] ]  }

functions:
  L1_Publish:
    handler: functions/l1Publish.handler
    #If you send a message to a topic, Amazon SNS delivers the message to each endpoint that is subscribed to the topic. 
    events:
      - http:
          path: /l1Publish/{myParam}
          method: get
          request:
            parameters:
              paths:
                myParam: true
    environment:
      snsTopicForConsumer1Arn: ${self:custom.snsTopicForConsumer1Arn.${self:provider.stage}}
            
  L2_Consume_Publish:
    handler: functions/l2ConsumePublish.handler
     #If you send a message to a topic, Amazon SNS delivers the message to each endpoint that is subscribed to the topic. 
    events:
      - sns: ${self:custom.snsTopicForConsumer1}
    environment:
        snsTopicForConsumer2Arn: ${self:custom.snsTopicForConsumer2Arn.${self:provider.stage}}
 
  L3_Consume:
    handler: functions/l3Consume.handler
    events:
      - sns: ${self:custom.snsTopicForConsumer2}
